### PR TITLE
CXF-8532: @Priority support for ParamConverterProvider

### PR DESCRIPTION
**Pull request by reta**
`@Priority` support for `ParamConverterProvider` providers

### CODE REVIEW

**Comment by reta** [comment]
@andymc12 mind please taking a look? Also, I've noticed `MicroProfileClientProviderFactory::createComparator` does not take `@Priority` into account for providers, it is not required by spec? (sorry didn't have time to check it myself).

**Comment by andymc12** [comment]
Hi @reta - I'm on holiday today and tomorrow, but I'll take a look when I
get back.  IIRC, MP Rest Client should take `@Priority` into account, but
maybe it isn't tested in the TCK (or maybe we've just been passing so far
by luck?).  Thanks for catching this!

**Comment by reta** [comment]
@andymc12 my apologies, double-checked the implementation, the `MicroProfileClientProviderFactory::createComparator` is all set, it uses `ContractComparator` which uses the delegating comparator (the one which confused me) but itself check the priorities.

**Review by andymc12 — APPROVED** [review]
Changes look good to me.  Thanks @reta!

**Comment by reta** [comment]
Thanks a mill, @andymc12 !

**Pull request merged**
