### PR TITLE
[CXF-7846] jaxrs client instantiator lifecycle and pluggability

### PR DESCRIPTION
**Pull request by rmannibucau**

### CODE REVIEW

**Comment by deki** [comment]
The change looks ok but why have you merged it with my previous commit?

**Comment by rmannibucau** [comment]
@deki happent with the rebase (I didn't realize "origin" was the wrong remote branch on this computer), is it an issue?

**Comment by deki** [comment]
I think this change should have an own commit with an own comment because it's not related to the version update of Spring.

**Comment by rmannibucau** [comment]
Superseeded by https://github.com/apache/cxf/pull/449

**Comment by deki** [comment]
Thanks. You can just force push to your branch next time.

**Pull request closed without merging**
