### PR TITLE
CXF-7198: Update Spring-Boot to 1.5.1 release

### PR DESCRIPTION
**Pull request by deki**

### CODE REVIEW

**Comment by sberyozkin** [comment]
See my comments to #232. The actual version upgrade does not change anything in CXF but a change a new major SprongBoot dep. This is not a bad idea in itself - but will we break 1.4.x SpringBoot users if we start inadvertently utilizing 1.5.x features where 1.4.x is still not exactly old ?

**Comment by sberyozkin** [comment]
In other words, given that it was confirmed CXF starters can now work with 1.5.x, I think that we should only upgrade to 1.5.x if we start using 1.5.x features inside CXF starters - to make sure CXF Spring Boot 1.4.x and 1.5.x users can use the startes

**Comment by deki** [comment]
Ok.

**Comment by sberyozkin** [comment]
I've opened https://issues.apache.org/jira/browse/CXF-7237 to get this issue tracked and be more visible, thanks

**Pull request closed without merging**
