### PR TITLE
[CXF-8140]:setAccessible(true) before reflection method java.security…

### PR DESCRIPTION
**Pull request by jimma**
….acl.Group#members invocation

### CODE REVIEW

**Comment by amarkevich** [comment]
Test passed even with existing impl:
```
    @Test
    public void testCheckGroup() {
        final String role = "role";
        Subject s = new Subject();
        Principal p = new SimplePrincipal(role);
        TestGroupPrincipal g = new TestGroupPrincipal("groupName", p);
        s.getPrincipals().add(g);
        LoginSecurityContext context = new DefaultSecurityContext(g, s);
        assertTrue(context.isUserInRole(role));
    }

    @SuppressWarnings("serial")
    private class TestGroupPrincipal extends SimpleGroup {
        TestGroupPrincipal(String groupName, Principal member) {
            super(groupName, member);
        }
        @Override
        public Enumeration<? extends Principal> members() {
            return super.members();
        }
    }
```

**Comment by jimma** [comment]
@amarkevich  I created a test case to demonstrate this issue: https://github.com/apache/cxf/pull/592/files#diff-4b7035cd3b166a7cce1f68d6a8bbc175R122

**Comment by amarkevich** [comment]
@jimma provided test still passed without `setAccessible(true)` both on jdk8u232-b09 & jdk-11.0.5+10
Method `public java.util.Enumeration org.apache.cxf.interceptor.security.GroupWrapper$SimpleGroup.members()` invokde successfuly

**Comment by jimma** [comment]
@amarkevich Strange thing. My local jvm is:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
Without setAccessible(true),  I always get this failure : 
```
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.02 s <<< FAILURE! - in org.apache.cxf.interceptor.security.DefaultSecurityContextTest
[ERROR] testPrivateStaticGroup(org.apache.cxf.interceptor.security.DefaultSecurityContextTest)  Time elapsed: 0.018 s  <<< FAILURE!
java.lang.AssertionError
	at org.apache.cxf.interceptor.security.DefaultSecurityContextTest.testPrivateStaticGroup(DefaultSecurityContextTest.java:131)
```

**Comment by jimma** [comment]
@amarkevich  Let me try to revert this change to see what's the jenkins result.

**Pull request merged**
