### PR TITLE
Upgrade jaxb runtime to 4.0.5

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Comment by reta** [comment]
I believe we have an issue with 4.0.5 :( , https://github.com/apache/cxf-xjc-utils/pull/135

**Comment by jimma** [comment]
It seems it's some javadoc wrong expectation issue in https://github.com/apache/cxf-xjc-utils/pull/135. Can we simply fix the JavadocPluginTest ?

```
ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.933 s <<< FAILURE! -- in org.apache.cxf.xjc.javadoc.JavadocPluginTest
[ERROR] org.apache.cxf.xjc.javadoc.JavadocPluginTest.testDocumentationOnPropertiesIsOverwrittenByJAXBBindings -- Time elapsed: 0.071 s <<< FAILURE!
java.lang.AssertionError:

Expected: not javadoc contains given comment: Some documentation of element
     but: was </**
 * Documentation from JAXB binding customization Some documentation of element
 */
>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.apache.cxf.xjc.javadoc.JavadocPluginTest.testDocumentationOnPropertiesIsOverwrittenByJAXBBindings(JavadocPluginTest.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
```

**Comment by reta** [comment]
> It seems it's some javadoc wrong expectation issue in [apache/cxf-xjc-utils#135](https://github.com/apache/cxf-xjc-utils/pull/135). Can we simply fix the JavadocPluginTest ?

Correct, I briefly looked at the test case before, it expects some overrides to  be respected, that was working fine pre-4.0.5 but breaks with new version. I will try to take a look shortly, thanks @jimma !

**Comment by reta** [comment]
I think we should be good to go, I pinpointed the change in question and merged https://github.com/apache/cxf-xjc-utils/pull/135, thanks @jimma !

**Review by reta — APPROVED** [review]

**Pull request merged**
