### PR TITLE
Avoid lock on read (issue: https://issues.apache.org/jira/browse/CXF-6825)

### PR DESCRIPTION
**Pull request by yotammadem**
This is seems to be a bottle neck in our performance tests

### CODE REVIEW

**Comment by dkulp** [comment]
You HAVE to have the lock on the get as well as the put.   During the put, the entire map is allowed to be restructured internally (buckets recalculated, etc... if the map grows) which would make anything going on in the get invalid.

**Comment by yotammadem** [comment]
So what do you suggest to do?
Maybe we should use some other data structure (one of the concurrent ones)?

**Comment by yotammadem** [comment]
What do you mean by invalid?
I understand that it can return null because it didn't find the thread in the map
but do you think it is really possible for it to return something else?

(in the case of null my code is treating it well)

**Comment by yotammadem** [comment]
I am closing this, will open other one when fix is ready

**Pull request closed without merging**
