### PR TITLE
[CXF-8716]:Migration path for Project Grizzly

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Review by asoldano — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Great one, thanks @jimma !

**Comment by jimma** [comment]
@reta  Great to see there are only 2 test system test failures left !

**Comment by reta** [comment]
> @reta Great to see there are only 2 system test failures left !

Great job @jimma !

**Comment by jimma** [comment]
> > @reta Great to see there are only 2 system test failures left !
> 
> Great job @jimma !

@reta  Kudos for your Jetty migration change ! That's the change fixed a lot of system test failures.

**Pull request merged**
