### PR TITLE
CXF-8028: try to fix performance for very big document in DOMUtils

### PR DESCRIPTION
**Pull request by gillesdiacon**
CXF-8028: try to fix performance for very big document in DOMUtils.getDomElement() and DOMUtils.getDomDocumentFragment()

### CODE REVIEW

**Comment by dkulp** [comment]
I believe this would be much better off using a java.lang.ClassValue to store the method (or null).   The reflection code would only happen once per class (good) and the value directly stored with the class so nothing is in a static that that would prevent garbage collection.

**Comment by coheigea** [comment]
@gillesdiacon - Does @dkulp 's suggestion sounds OK for you? It would be good to get this fix into the next CXF release.

**Comment by dkulp** [comment]
I committed a fix that uses the ClassValue approach.  The test you provided shows a massive speed increase which is awesome.   Major thanks for identifying the issue.

Fix is in 1cc03b9b70bc509d8f8c631563c3964e56e30621

**Comment by gillesdiacon** [comment]
@dkulp: sorry for lack of reaction. Your proposition is very good and better than my static sets :-)

**Pull request closed without merging**
