### PR TITLE
support contextProperties to utilize, e.g. eclipselink.beanvalidation…

### PR DESCRIPTION
**Pull request by slavb18**
support contextProperties to utilize, e.g. eclipselink.beanvalidation.facets

### CODE REVIEW

**Comment by sberyozkin** [comment]
Thanks for the patch, I've added a 'jaxb' prefix to the property name given that using JAXB can be optional and other strategies can be used

**Comment by slavb18** [comment]
Sergey, can I now supply such patch for 3.1.11 branch ?

**Comment by sberyozkin** [comment]
I've already back merged it into 3.1.11-SNAPSHOT

**Comment by slavb18** [comment]
Thanks!

**Pull request closed without merging**
