### PR TITLE
[CXF-6424] AbstractLoggingInterceptor tests and improvements

### PR DESCRIPTION
**Pull request by skjolber**
See JIRA issue for further details

### CODE REVIEW

**Comment by cschneider** [comment]
The new code changes the behaviour for truncated messages. In the current code the result is always well formed xml. The new code for example sometimes omits closing tags. This is not correct.

**Comment by tomitribe-dev** [comment]
Build triggered. sha1 is merged.

**Comment by deki** [comment]
Please rebase and check if the changes are still needed. AbstractLoggingInterceptor from cxf-core is deprecated, there is now org.apache.cxf.ext.logging.AbstractLoggingInterceptor in cxf-rt-features-logging.

**Comment by skjolber** [comment]
I actually deleted my fork, but I'll review the conflicting changes and possibly rebase.

**Pull request closed without merging**
