### PR TITLE
[CXF-7579] More config impl.

### PR DESCRIPTION
**Pull request by johnament**
@andymc12  I'm not sure if this makes it worse.  I'm now seeing the call hit the server (I have something on port 80).

### CODE REVIEW

**Comment by johnament** [comment]
I have to dig in further, but it seems that the priority registered is ignored for client request filters, they don't go through the sorting algorithm.

**Comment by johnament** [comment]
@andymc12  I'm going to bring my branch into the repo shortly.  What were your thoughts on how to handle the interface validation?  There is nothing in CXF today.

**Comment by andymc12** [comment]
@johnament 
> What were your thoughts on how to handle the interface validation?

My thought was that we would add some validation code in the `CxfTypeSafeClientBuilder.build(...)` method.  That way, we avoid doing expensive things like looking up providers, etc. if the interface is bad.

**Comment by johnament** [comment]
@andymc12  FYI, if you want to take a look

```
java.lang.IllegalStateException: The entity is not backed by an input stream, entity class is : java.lang.String
	at org.eclipse.microprofile.rest.client.tck.CustomHttpMethodTest.invokesUserDefinedHttpMethod(CustomHttpMethodTest.java:52)
```

**Pull request merged**
