### PR TITLE
CXF-7708 Options mark-generated and suppress-generated-date don't effect on generating Java classes

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by deki** [comment]
@typekpb fyi

**Comment by typekpb** [comment]
Well, I've noticed that with the latest version of cxf it didn't work. So
would be very thankful for the fix.

**Comment by deki** [comment]
Hmm I wonder why does the unittest not fail? If this is a different case, could you please add one for it so that we are covered in future?

**Comment by deki** [comment]
Ok, would it be possible for one of you to add a unit test, please?

**Comment by dmvolod** [comment]
Yes, working on it for codegen plugin, but looks like no enforce plugin configured for build and integration test fails don't broke build pipeline. Also it contains jdk6 test which is always fails and i don't know is it actual or not.

**Comment by deki** [comment]
I think the jdk6 testcase is no longer valid for 3.2.x but we should probably have one for toolchains. I try to modify it and switch the invoker-plugin to break the build afterwards...

**Comment by deki** [comment]
Ok the build now fails but I had to disable the toolchain test due to CXF-7714.

**Comment by dmvolod** [comment]
@deki , i've added it and fix current build process. Please review.

**Pull request merged**
