### PR TITLE
CXF-8714: Migration path for Swagger v1.x

### PR DESCRIPTION
**Pull request by reta**
It seems like Swagger 1.x is not planned to support Jakarta, we would need to drop this integration

### CODE REVIEW

**Comment by reta** [comment]
@jimma @ffang could you please take a look guys, if it makes sense to you, thank you!

**Comment by jimma** [comment]
@reta  Should these swagger test resource files under https://github.com/reta/cxf/tree/CXF-8714/systests/jaxrs/src/test/resources/org/apache/cxf/systest/jaxrs/description be removed too ?

**Review by deki — APPROVED** [review]
Makes sense to drop it for 1.x

**Comment by reta** [comment]
> @reta LGTM . More test resource files we can probably remove them too ?
> 
>     * Files under https://github.com/reta/cxf/tree/CXF-8714/systests/jaxrs/src/test/resources/org/apache/cxf/systest/jaxrs/description
> 
>     * https://github.com/reta/cxf/blob/CXF-8714/systests/jaxrs/src/test/resources/files/swagger.properties.

@jimma absolutely, missed that, thank you for noticing, removed resources as well

**Comment by coheigea** [comment]
LGTM, need to rebase

**Pull request merged**
