### PR TITLE
CXF-7682: context.get(MessageContext.HTTP_REQUEST_HEADERS) always ret…

### PR DESCRIPTION
**Pull request by sanaik22**
…urns null for client

### CODE REVIEW

**Comment by jimma** [comment]
@sanaik22 Can you please add a test for this change ?

**Comment by asoldano** [comment]
@TomasHofman I've triggered another run, let's see how it goes..

**Comment by dkulp** [comment]
@asoldano : If this clears, I'll merge it, but you may want to do a TCK run with the change prior to our next CXF release.  For some reason, I seem to remember some weird context return value issues that the TCK hit for the various handler types.

**Comment by asoldano** [comment]
@dkulp yes, definitely (@jimma FYI)

**Comment by dkulp** [comment]
Merging, lgtm.

**Pull request merged**
