### PR TITLE
Refactor assertFalse(equals()) using assertNotEquals & Refactor assertTrue(equals()) using assertEquals

### PR DESCRIPTION
**Pull request by Taher-Ghaleb**
I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice. 

For example, the smell in [NameSpaceTest.java](https://github.com/apache/cxf/pull/1395/files#diff-222a3706aae4f8dd30c4e5e1953ed3d6fca3d04085e56e4bce43466369ed282c) occurs when inappropriate assertions, such as `assertFalse(nsDecl2.equals(nsDecl1));` are used, while there exist better alternatives, such as `assertNotEquals(nsDecl1, nsDecl2);`.

We would like to get your feedback on these particular test smells and their refactorings. Thanks in advance for your input.

### CODE REVIEW

**Comment by amarkevich** [comment]
Hi @Taher-Ghaleb 
Thanks for contribution
Try to replace all smells using regexp search "assertFalse.*equals"

**Comment by Taher-Ghaleb** [comment]
Thanks, @amarkevich, for your response. I replaced all the occurrences of assertFalse(equals()) with assertNotEquals, where applicable.

Please check and let me know your opinion about such refactorings. Your feedback is appreciated.

**Comment by amarkevich** [comment]
> replaced all the occurrences of assertFalse(equals()) with assertNotEquals

Could you proceed with "assertTrue.*equals" too?
Since there is only single assertThrows change - I propose to keep it as is and make scope of changes about assertTrue/assertFalse + equal as evaluated  argument -> assertEquals/assertNotEquals

**Comment by Taher-Ghaleb** [comment]
I checked "assertTrue.*equals" but I found out that in almost all cases, the equality-checking methods are specialized (e.g., `boolean equals`, `boolean equalsTime`, etc.) and hence refactoring them may not produce the expected results.

I searched for  "assertTrue.*!equals", which could be refactored using _assertNotEquals_ as well, but didn't find any cases.

For _assertThrows_, I actually found many refactoring opportunities in different test files, but I can do it in a separate pull request, to make the scope of this one for equality assertions, as you suggested.

**Comment by Taher-Ghaleb** [comment]
> There are still a couple of simple check with single equal

I refactored them.

**Comment by amarkevich** [comment]
> Please check.

Below is failed build - please fix regression.
And keep assertThrows changes for other topic - to be concrete in scope of changes.

**Comment by Taher-Ghaleb** [comment]
Fixed. Hope it passes now, but if not, I'll fix it. Thanks.

**Comment by Taher-Ghaleb** [comment]
Hi @amarkevich. I'm not sure if the build failure now is related to my changes. I checked the build log and seems to be due to a timeout. Please let me know if I need to fix something. Thanks.

**Comment by reta** [comment]
> Hi @amarkevich. I'm not sure if the build failure now is related to my changes. I checked the build log and seems to be due to a timeout. Please let me know if I need to fix something. Thanks.

The failures look legit and caused by this pull request:

```
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project cxf-systests-uncategorized: Compilation failure: Compilation failure: 
Error:  /home/runner/work/cxf/cxf/systests/uncategorized/src/test/java/org/apache/cxf/systest/type_test/AbstractTypeTestClient3.java:[2240,17] no suitable method found for assertEquals(java.lang.String,java.util.List<java.lang.Short>,java.util.List<java.lang.Short>)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.StructWithList,org.apache.type_test.types1.StructWithList) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.StructWithList)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.StructWithUnion,org.apache.type_test.types1.StructWithUnion) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.StructWithUnion)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.UnionSimpleContent,org.apache.type_test.types1.UnionSimpleContent) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.UnionSimpleContent)
Error:  /home/runner/work/cxf/cxf/systests/uncategorized/src/test/java/org/apache/cxf/systest/type_test/AbstractTypeTestClient3.java:[2241,17] no suitable method found for assertEquals(java.lang.String,java.util.List<java.lang.Short>,java.util.List<java.lang.Short>)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.StructWithList,org.apache.type_test.types1.StructWithList) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.StructWithList)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.StructWithUnion,org.apache.type_test.types1.StructWithUnion) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.StructWithUnion)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.UnionSimpleContent,org.apache.type_test.types1.UnionSimpleContent) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.UnionSimpleContent)
Error:  /home/runner/work/cxf/cxf/systests/uncategorized/src/test/java/org/apache/cxf/systest/type_test/AbstractTypeTestClient3.java:[2242,17] no suitable method found for assertEquals(java.lang.String,java.util.List<java.lang.Short>,java.util.List<java.lang.Short>)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.StructWithList,org.apache.type_test.types1.StructWithList) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.StructWithList)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.StructWithUnion,org.apache.type_test.types1.StructWithUnion) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.StructWithUnion)
Error:      method org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(java.lang.String,org.apache.type_test.types1.UnionSimpleContent,org.apache.type_test.types1.UnionSimpleContent) is not applicable
Error:        (argument mismatch; java.util.List<java.lang.Short> cannot be converted to org.apache.type_test.types1.UnionSimpleContent)
Error:  -> [Help 1]
Error:  
```

**Comment by Taher-Ghaleb** [comment]
I see. Yes, the recent build now shows the failures. I’ll fix them shortly.

**Comment by amarkevich** [comment]
compilation failure is due to `org.apache.cxf.systest.type_test.AbstractTypeTestClient2.assertEquals(String, StructWithList, StructWithList)`. Use `Assert.assertEquals` to fix that

**Pull request merged**
