### PR TITLE
CXF-7506: Upgrade guava

### PR DESCRIPTION
**Pull request by davidkarlsen**

### CODE REVIEW

**Comment by deki** [comment]
Thanks for your PR. Have you checked for OSGi compatibility? we had several conflicts in the past...

**Comment by davidkarlsen** [comment]
No - I did not - and the build broke - downloading the internet and running locally now...

**Comment by sberyozkin** [comment]
Hi, why is this update needed, we usually update guava if some of the CXF features indirectly needs it, example, CXF needs to update a newer swagger-core/etc which requires newer guava

**Comment by davidkarlsen** [comment]
AFAIK it is not needed - I just found the JIRA issue sticking around for the target release.

**Comment by sberyozkin** [comment]
Thanks; yes, IMHO it would make sense to postpone until the newer Guava version is actually needed

**Comment by davidkarlsen** [comment]
Agreed - close the jira and abandon this.

**Pull request closed without merging**
