### PR TITLE
[CXF-5118] Create CXF interceptor which will use HTTPS client certificat...

### PR DESCRIPTION
**Pull request by PiotrKlimczak**
...es to create JAAS SecurityContext

### CODE REVIEW

**Comment by tomitribe-dev** [comment]
Build triggered. sha1 is merged.

**Comment by tomitribe-dev** [comment]
Build started sha1 is merged.

**Comment by tomitribe-dev** [comment]
Build finished. 0 tests run, 0 skipped, 0 failed.

**Comment by deki** [comment]
CXF-5118 is resolved so this should be closed as well, shouldn't it?

**Pull request closed without merging**
