### PR TITLE
Include details of validation exceptions in response in ValidationExceptionMapper

### PR DESCRIPTION
**Pull request by slavb18**
This PR contains of
1) addMessageToResponse flag to include validation errors in response
2) messageTemplate to set custom message format

### CODE REVIEW

**Comment by sberyozkin** [comment]
Unfortunately we can not introduce Spring dependencies into this code. The simplest option to customize is to register a custom ValidationExceptionMapper

**Comment by slavb18** [comment]
ok, thanks

**Comment by slavb18** [comment]
and how about addMessageToResponse?

**Comment by sberyozkin** [comment]
I've applied the patch with the minor modifications, thanks. I've only made StringBuilder instantiation optional, and kept the original message format. I'm open though to add 'Value of' - how does the message would read with it ? I hesitated because a constraint violation has a method like .getInvalidValue()

**Pull request closed without merging**
