### PR TITLE
CXF-8371: Support Jakarta EE 9.1+

### PR DESCRIPTION
**Pull request by reta**
Jakarta EE Platform 9.1 specs (used by CXF and integrations):
 - Jakarta Activation 2.0
 - Jakarta Annotations 2.0
 - Jakarta Bean Validation 3.0
 - Jakarta Connectors 2.0
 - Jakarta Contexts and Dependency Injection 3.0
 - Jakarta Dependency Injection 2.0
 - Jakarta Enterprise Beans 4.0
 - Jakarta Enterprise Web Services 2.0 (Optional)
 - Jakarta Expression Language 4.0
 - Jakarta Interceptors 2.0
 - Jakarta JSON Binding 2.0
 - Jakarta JSON Processing 2.0
 - Jakarta Mail 2.0
 - Jakarta Messaging 3.0
 - Jakarta Persistence 3.0
 - Jakarta RESTful Web Services 3.0
 - Jakarta Security 2.0
 - Jakarta Servlet 5.0
 - Jakarta SOAP with Attachments 2.0 
 - Jakarta Transactions 2.0
 - Jakarta WebSocket 2.0
 - Jakarta Web Services Metadata 3.0 
 - Jakarta XML Binding 3.0 (Optional)
 - Jakarta XML Web Services 3.0 

TODOs:
- [x] cxf-xjc-plugin
- [ ] Swagger v1 (https://issues.apache.org/jira/browse/CXF-8714)
- [ ] Microprofile OpenAPI (https://issues.apache.org/jira/browse/CXF-8715)
- [X] Swagger v2 / OpenAPI
- [ ] Project Grizzly (https://javaee.github.io/grizzly/) (https://issues.apache.org/jira/browse/CXF-8716)
- [x] Jetty Continuations (https://github.com/eclipse/jetty.project/issues/4934) are gone
- [ ] Jakarta WebSocket (including Jetty WebSocket) (https://issues.apache.org/jira/browse/CXF-8717)
- [X] Jackson
- [x] ActiveMQ (https://blogs.apache.org/activemq/entry/activemq-artemis-embraces-jakarta-ee), no support for Jakarta
- [ ] Brave / Opentracing (instrumentation) (https://issues.apache.org/jira/browse/CXF-8718, https://issues.apache.org/jira/browse/CXF-8719)
- [ ] Atmosphere
- [X] Weld 
- [ ] OpenWebBeans (no JDK-17 support as of 2.0.26) (https://issues.apache.org/jira/browse/CXF-8721)
     ```
    Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	    at org.apache.xbean.asm9.ClassReader.<init>(ClassReader.java:189)
	    at org.apache.xbean.asm9.ClassReader.<init>(ClassReader.java:170)
	    at org.apache.xbean.asm9.ClassReader.<init>(ClassReader.java:156)
	    at org.apache.xbean.asm9.ClassReader.<init>(ClassReader.java:277)
	    at org.apache.xbean.finder.AnnotationFinder.readClassDef(AnnotationFinder.java:1176)
	    ... 53 more
     ```
- [ ] Apache Karaf (https://issues.apache.org/jira/browse/CXF-8722)
- [ ] OSGi (https://issues.apache.org/jira/browse/CXF-8723)
    - [ ] remove "transports-http" OSGi exclusions (https://github.com/apache/cxf/blob/CXF-8371/rt/transports/http/pom.xml#L285)
- [X] Ehache3 

Temporary excluded modules (could be activated with `-Pjavax` profile, see please https://github.com/apache/cxf/pull/931) (https://issues.apache.org/jira/browse/CXF-8724):
  - `<module>wadl2java-plugin</module>`
  - `<module>java2swagger-plugin</module>`
  - `<module>osgi</module>`
  - `<module>description-swagger</module>`
  - `<module>description-microprofile-openapi</module>`
  - `<module>websocket</module>`
  - `<module>grizzly</module>`
  - `<module>jaxrs</module>`
  - `<module>codegen</module>`

### CODE REVIEW

**Comment by coheigea** [comment]
@reta The rt/rs/security/sso/saml tests are failing with:

Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventHandler

I see there is a separate jakarta jar for ehcache - I'm not sure how to pick this up in CXF though?

**Comment by reta** [comment]
> @reta The rt/rs/security/sso/saml tests are failing with:
> 
> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventHandler
> 
> I see there is a separate jakarta jar for ehcache - I'm not sure how to pick this up in CXF though?

Should be fixed now, thanks @coheigea !

**Comment by coheigea** [comment]
Thanks @reta. When I try to upgrade WSS4J to use ehcache 3.10.0 I get this error, any ideas?

[ERROR] Failed to execute goal on project wss4j-ws-security-common: Could not resolve dependencies for project org.apache.wss4j:wss4j-ws-security-common:jar:3.0.0-SNAPSHOT: Failed to collect dependencies at org.ehcache:ehcache:jar:3.10.0 -> org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453 -> org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453 -> javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Failed to read artifact descriptor for javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Could not transfer artifact javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [releases.java.net (http://maven.java.net/content/repositories/releases/, default, releases+snapshots), shapshots.java.net (http://maven.java.net/content/repositories/snapshots/, default, releases+snapshots), jvnet-nexus-staging (http://maven.java.net/content/repositories/staging/, default, releases+snapshots), netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans, default, releases)]

**Comment by coheigea** [comment]
The JPA tests are failing in rt/rs/security/oauth-parent/oauth2 - do we need to follow https://rmannibucau.metawerx.net/openjpa-jakarta-tips.html ?

**Comment by reta** [comment]
> Thanks @reta. When I try to upgrade WSS4J to use ehcache 3.10.0 I get this error, any ideas?
> 

@coheigea it seems like the repositories are not set properly: http:// is blocked. I could take a look, is it for https://github.com/apache/santuario-xml-security-java?

**Comment by reta** [comment]
> The JPA tests are failing in rt/rs/security/oauth-parent/oauth2 - do we need to follow https://rmannibucau.metawerx.net/openjpa-jakarta-tips.html ?

Yeah, we are trying to go module by module :-) but I will check the `security` since it is in a good shape now, thanks @coheigea !

**Comment by coheigea** [comment]
Thanks, it's in https://github.com/apache/ws-wss4j

**Comment by jimma** [comment]
@reta @coheigea  Should we update the version to 5.0.0-SNAPSHOT ? If there is no objection,I'll start to update version number tomorrow.

**Comment by reta** [comment]
> @reta @coheigea Should we update the version to 5.0.0-SNAPSHOT ? If there is no objection,I'll start to update version number tomorrow.

@jimma why 5.0.0? As we discussed, 4.0 is Jakarta, the 3.x would be the `javax.*` line, the thread is there [1]

[1] https://www.mail-archive.com/dev@cxf.apache.org/msg17023.html

**Comment by jimma** [comment]
> > @reta @coheigea Should we update the version to 5.0.0-SNAPSHOT ? If there is no objection,I'll start to update version number tomorrow.
> 
> @jimma why 5.0.0? As we discussed, 4.0 is Jakarta, the 3.x would be the `javax.*` line, the thread is there [1]
> 
> [1] https://www.mail-archive.com/dev@cxf.apache.org/msg17023.html

@reta  CXF master is now 4.0.0-SNAPSHOT : https://github.com/apache/cxf/blob/master/pom.xml#L24
There are still a lot of changes/fixes on this branch.  So there is no plan to tag a 4.0.0 and following 4.x release, right ?

**Comment by reta** [comment]
> > > @reta @coheigea Should we update the version to 5.0.0-SNAPSHOT ? If there is no objection,I'll start to update version number tomorrow.
> > 
> > 
> > @jimma why 5.0.0? As we discussed, 4.0 is Jakarta, the 3.x would be the `javax.*` line, the thread is there [1]
> > [1] https://www.mail-archive.com/dev@cxf.apache.org/msg17023.html
> 
> @reta CXF master is now 4.0.0-SNAPSHOT : https://github.com/apache/cxf/blob/master/pom.xml#L24 There are still a lot of changes/fixes on this branch. So there is no plan to tag a 4.0.0 and following 4.x release, right ?

Correct, as far as I remember, we decided to keep master on 4.x (Jakarta) branch. We should probably branch of 3.6.x-fixes (from the `master`) soon so continue the 3.x line development, makes sense? @coheigea wdyt?

**Comment by reta** [comment]
> @reta If we'll change the master 4.0 to jakarta, I think we can plan some Alpha or milestone release to include the things already work. At least we make the CI work, and community can easily contribute patch and improve the jakarta CXF, and we don't maintain more branches. WDYT ?

@jimma sorry, lost a bit here: master is 4.0.0 / `Jakarta` (we just have the changes behind the pull request but I think we could go ahead and merge them soon). The `javax.*` still has to be supported (as we discussed), logically leading to 2 main branches: jakarta.* and javax.*

**Comment by jimma** [comment]
@reta  I meant when can we merge the CXF-8371 to master ?  And we probably need plan some Alpha or Milestone release in the jakarta 4.x CXF and make CI work , then we don 't need to maintain the CXF-8371 branch anymore.

**Comment by reta** [comment]
> @reta I meant when can we merge the CXF-8371 to master . And we probably need plan some Alpha or Milestone release in the jakarta 4.x CXF and make CI work , then we don 't need to maintain the CXF-8371 branch anymore.

@jimma I don't have any objections, ideally it would be great to megre when at least major issues (listed in description) are addressed but it could take a while.  But realistically, once JMS (migration to Artemis) is ready, nothing is pending for this branch and we could get it to master. @coheigea @ffang what do you think guys?

CI is actually running on every commit [1]

[1] https://ci-builds.apache.org/job/CXF/job/pipeline/job/CXF-8371

**Comment by coheigea** [comment]
No objections from me to merging to master, so long as we create JIRAs for the outstanding tasks.

**Comment by jimma** [comment]
> > @reta I meant when can we merge the CXF-8371 to master . And we probably need plan some Alpha or Milestone release in the jakarta 4.x CXF and make CI work , then we don 't need to maintain the CXF-8371 branch anymore.
> 
> @jimma I don't have any objections, ideally it would be great to megre when at least major issues (listed in description) are addressed but it could take a while. But realistically, once JMS (migration to Artemis) is ready, nothing is pending for this branch and we could get it to master. @coheigea @ffang what do you think guys?
> 
> CI is actually running on every commit [1]
> 
> [1] https://ci-builds.apache.org/job/CXF/job/pipeline/job/CXF-8371

@reta  Good to know this is already works. Is it better to add the "-fae" flag to see all the test failures ?  
I wrongly saw this CI result : https://ci-builds.apache.org/job/CXF/job/CXF-JDK11-PR/109/, it's still using JDK11 to run. It's good to fix this too.  WDYT ?

**Comment by reta** [comment]
> > > @reta I meant when can we merge the CXF-8371 to master . And we probably need plan some Alpha or Milestone release in the jakarta 4.x CXF and make CI work , then we don 't need to maintain the CXF-8371 branch anymore.
> > 
> > 
> > @jimma I don't have any objections, ideally it would be great to megre when at least major issues (listed in description) are addressed but it could take a while. But realistically, once JMS (migration to Artemis) is ready, nothing is pending for this branch and we could get it to master. @coheigea @ffang what do you think guys?
> > CI is actually running on every commit [1]
> > [1] https://ci-builds.apache.org/job/CXF/job/pipeline/job/CXF-8371
> 
> @reta Good to know this is already works. Is it better to add the "-fae" flag to see all the test failures ? 

Done, https://ci-builds.apache.org/job/CXF/job/pipeline/job/CXF-8371/38/consoleFull

> I wrongly saw this CI result : https://ci-builds.apache.org/job/CXF/job/CXF-JDK11-PR/109/, it's still using JDK11 to run. It's good to fix this too. WDYT ?

This is the right place since this is a PR build (but we also build `origin` branch pipelines). The thing is, this is our main Jenkins check for `master` - basically where we have all pull requests coming. For `javax.*` we will stay on JDK-11 baseline (as we discussed [1]) so it is probably makes sense to keep it that way. But ... for Jakarta branch (4.0.0) we would need it to use JDK-17 and to be fair, I have not succeeded yet to configure separate pull request builders for different branches. I mean, I could create Jenkins jobs for different branch specs but only one of the jobs triggers. Will be looking into that shortly.

[1] https://www.mail-archive.com/dev@cxf.apache.org/msg17023.html

**Comment by jimma** [comment]
> 
> Done, https://ci-builds.apache.org/job/CXF/job/pipeline/job/CXF-8371/38/consoleFull
> 

Thanks for the quick change.  The test result is out :https://ci-builds.apache.org/job/CXF/job/pipeline/job/CXF-8371/41/#showFailuresLink and it's not bad. 


> This is the right place since this is a PR build (but we also build `origin` branch pipelines). The thing is, this is our main Jenkins check for `master` - basically where we have all pull requests coming. For `javax.*` we will stay on JDK-11 baseline (as we discussed [1]) so it is probably makes sense to keep it that way. But ... for Jakarta branch (4.0.0) we would need it to use JDK-17 and to be fair, I have not succeeded yet to configure separate pull request builders for different branches. I mean, I could create Jenkins jobs for different branch specs but only one of the jobs triggers. Will be looking into that shortly.
> 
> [1] https://www.mail-archive.com/dev@cxf.apache.org/msg17023.html

Thanks for the update @reta.

**Comment by ffang** [comment]
> > @reta I meant when can we merge the CXF-8371 to master . And we probably need plan some Alpha or Milestone release in the jakarta 4.x CXF and make CI work , then we don 't need to maintain the CXF-8371 branch anymore.
> 
> @jimma I don't have any objections, ideally it would be great to megre when at least major issues (listed in description) are addressed but it could take a while. But realistically, once JMS (migration to Artemis) is ready, nothing is pending for this branch and we could get it to master. @coheigea @ffang what do you think guys?
> 
> CI is actually running on every commit [1]
> 
> [1] https://ci-builds.apache.org/job/CXF/job/pipeline/job/CXF-8371

@reta @jimma no objections to merge the Jakarta work to CXF 4.0 branch.

Thanks for the effort guys!
Freeman

**Comment by jimma** [comment]
Thanks for you all for review and comment. @coheigea  Is it close to release wss4j to upgrade the 3.0.0 in jakarta/master branch ?

**Comment by coheigea** [comment]
Yes pretty close @jimma , I can call a vote say the week after next?

**Comment by jimma** [comment]
@reta  Is it close to tag and release the cxf-xjc-utils 4.0.0 too ?

**Comment by reta** [comment]
> @reta Is it close to tag and release the cxf-xjc-utils 4.0.0 too ?

Yeah I think so (I just need to update the build-tools dependency from snapshot),  @coheigea do you mind to send the vote for 3.x (as we discussed) and 4.0.0 (if no objections)?  Thank you!

**Comment by jimma** [comment]
@reta  Should we upgrade the build tools version to 4.0.0 in xjc-utils ? I sent a PR to upgrade this version. Please review : https://github.com/apache/cxf-xjc-utils/pull/12

**Comment by coheigea** [comment]
Shouldn't we just release 4.0.0 of build-tools first?

**Comment by reta** [comment]
> Shouldn't we just release 4.0.0 of build-tools first?

@coheigea That would be better, we could than release  `cxf-xjc-utils` for 3.x and 4.x, thank you!

**Comment by coheigea** [comment]
OK, I did XJC 3.3.2 today, I'll do the build-utils 4.0.0 next week and then XJC 4.0.0 when it's released.

**Comment by reta** [comment]
@coheigea @jimma I think we could get it into `master`, I will create JIRA tickets on each issue listed in description to track the progress, wdyt guys? :-)

**Comment by jimma** [comment]
@reta That's great!  Please go ahead.

**Comment by medliii** [comment]
Excuse me, is there a tag for this merged PR at https://mvnrepository.com/ ?
I'am trying generate client via cxf-codegen-plugin:[3.5.3](https://mvnrepository.com/artifact/org.apache.cxf/cxf-codegen-plugin/3.5.3) and it generates javax libraries instead of jakarta

**Comment by coheigea** [comment]
@medliii The fix version for https://issues.apache.org/jira/browse/CXF-8371 is 4.0.0, it is not yet released.

**Comment by Shabin** [comment]
For [CXF-8675](https://issues.apache.org/jira/browse/CXF-8675) this commit [Workaround for ModuleUtil error in jaxb api](https://github.com/apache/cxf/pull/912/commits/73bfcf16f6c878532d1ccd3274515b5beb67145f) has hard coded `org.glassfish.jaxb.runtime.v2.ContextFactory`. 
So if I want to use another context factory like moxy what is the option to do so? I tried setting JAXBDataBinding properties and adding jaxb.properties and none of them worked.

**Comment by reta** [comment]
> So if I want to use another context factory like moxy what is the option to do so?

At the moment CXF does not support other JAXB implementations, see please https://issues.apache.org/jira/browse/CXF-5131

**Comment by Shabin** [comment]
It was possible in earlier versions by setting javax.xml.bind.context.factory in jaxb.properties. But now it is not possible since glassfish is hardcoded.

**Pull request merged**
