### PR TITLE
[CXF-7132] Use the original class when it comes to determining classe…

### PR DESCRIPTION
**Pull request by johnament**
…s for ResourceProvider usage.

### CODE REVIEW

**Comment by johnament** [comment]
Looks like the failures are not related to CDI... https://builds.apache.org/job/CXF-Trunk-PR/200/

**Comment by reta** [comment]
Thanks a lot for the fix, @johnament, will work on merging tonight

**Comment by rmannibucau** [comment]
should loadResourceProviders support not normal-scoped instances too (doesn't ATM it seems)?

**Comment by johnament** [comment]
@rmannibucau you are correct, there is a regression problem with non-normal scoped beans.  The code works.  Specifically for dependent and singleton, since they're not using proxies, the instance you get back is the same.  This essentially makes dependent == singleton.

You can see that the test does include both normal scoped and dependent beans https://github.com/johnament/cxf/tree/81e9215b75c02a6b108e94f474b9aa6011c8f00c/systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base - look at BookStore and VersionService as examples.

The code does work, but I would expect a per-request pattern to be used for dependent.  More refinement required to clean up this CDI integration.

**Comment by rmannibucau** [comment]
@johnament think singleton per default is fine (even good) but I don't think it works. Add a @PreDestroy releasing a socket pool (http pool to get some meta config for instance) and you will just leak this since the creational context is not released.

**Comment by reta** [comment]
@rmannibucau @johnament I think the CdiResourceProvider should be involved more here. The creation context could be released when `release` call happens.

**Comment by johnament** [comment]
@rmannibucau yes, that is the other problem.  But that's been a long standing issue with leaking instances, way before my time.  I'll clean that up though.  Raised https://issues.apache.org/jira/browse/CXF-7134

@reta Yes, I agree.  That's where I plan to put the `release`.

**Comment by johnament** [comment]
Ok, I added a couple more commits to this.  I'm not 100% happy with CXF-7134 but don't want to block a potential release.

What I'm seeing is that validation feature doesn't get registered on the JAX-RS resource when I move the creational context to the point of getting the instance.  Need to debug a bit further, but I think this is OK to merge for now.  Just leave 7134 open I'll clean up further.

**Comment by reta** [comment]
Hey @johnament , could you please create a separate PRs for these commits? I am about to close the original one, related to @RequestScoped. Now things may get complicated :-) 
Thanks!

**Comment by johnament** [comment]
I can.  I wasn't sure if you were holding off due to the conversation here.

**Comment by reta** [comment]
I taken the approach we have discussed, moving more responsibilities to CdiResourceProvider, I think I have gotten a bit cleaner implementation.

**Pull request closed without merging**
