### PR TITLE
add client digest interceptor

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
@coheigea

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@coheigea any thoughts on this one?
BTW: Are updated snapshots pushed out anywhere? I have a library to adapt to 3.3.2

**Comment by coheigea** [comment]
Yes see here: https://repository.apache.org/content/groups/snapshots/org/apache/cxf/cxf-rt-rs-security-http-signature/3.3.2-SNAPSHOT/

**Comment by davidkarlsen** [comment]
@coheigea I had missed calling proceed().
I have an alternative implementation which looks more similar to the jws stuff and wraps the output stream in a cachedOutputStream if you are interested in taking a look? I could add it as a separate PR?

**Comment by coheigea** [comment]
@davidkarlsen - I'll take care of adding the tests. The latest code is still not working, if you look at SignatureHeaderUtils.createDigestHeader, the messageBody String is actually blank. Maybe use the JWS approach instead in this PR?

**Pull request merged**
