### PR TITLE
[CXF-8535] Query missing from signature request-target

### PR DESCRIPTION
**Pull request by eberntsen**
Changed Interceptor and Filter to include query component in request-target.

Added test methods to include interceptor/filter in testing the cases from the spec. These tests previously only tested the objects used within the interceptor/filter (MessageSigner/Verifier) which led to this issue not being discovered by tests.

I also had to include PowerMock to mock the static PhaseInterceptorChain class used by the VerifySignatureFilter.

### CODE REVIEW

**Comment by eberntsen** [comment]
@coheigea can you please have a look at this PR?

**Comment by coheigea** [comment]
Please correct the checkstyle failures:

[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/utils/SignatureHeaderUtils.java:109:9: 'if' is not followed by whitespace. [WhitespaceAround]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/CreateSignatureInterceptor.java:32:1: Wrong order for 'javax.annotation.Priority' import. [ImportOrder]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/CreateSignatureInterceptor.java:45:1: Wrong order for 'java.io.IOException' import. [ImportOrder]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/CreateSignatureInterceptor.java:87: Line is longer than 120 characters (found 133). [LineLength]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/VerifySignatureFilter.java:23:1: Wrong order for 'java.io.ByteArrayInputStream' import. [ImportOrder]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:33:1: Wrong order for 'org.powermock.core.classloader.annotations.PrepareForTest' import. [ImportOrder]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:36:1: Wrong order for 'javax.ws.rs.client.ClientRequestContext' import. [ImportOrder]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:41:1: Wrong order for 'java.io.ByteArrayInputStream' import. [ImportOrder]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:58:8: Unused import - java.util.stream.Collectors. [UnusedImports]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:61:53: Using the '.*' form of import should be avoided - org.powermock.api.mockito.PowerMockito.*. [AvoidStarImport]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:169: Line is longer than 120 characters (found 124). [LineLength]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:244: Line is longer than 120 characters (found 124). [LineLength]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:321: Line is longer than 120 characters (found 124). [LineLength]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:328: Line is longer than 120 characters (found 133). [LineLength]
[ERROR] /home/coheig/src/apache/cxf/rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java:337: Line is longer than 120 characters (found 145). [LineLength]

**Comment by coheigea** [comment]
Overall LGTM, but I don't understand why the previous unit tests didn't fail, given that they were including a query parameter and we were testing against a Signature expected header, once the patch changed it to also sign the query shouldn't the signature header have been different?

**Comment by eberntsen** [comment]
Fixed checkstyle issues now.

The previous unit tests didn't fail previously because they didn't target any classes that had any issues. They don't fail now either because I haven't touched the existing methods, only added methods that tested other classes. The problem here was that the tests only manually tested the inner Signer/Verifier classes, but the issue was with the Interceptor/Filter layer. The Interceptor/Filter didn't give the inner classes the same input as the tests did.

**Review by coheigea — APPROVED** [review]

**Pull request merged**
