### PR TITLE
Reimplementing SSE using AsyncContext (Servlet 3.0+)

### PR DESCRIPTION
**Pull request by reta**
The PR is based solely on the contribution by @csierra (https://github.com/apache/cxf/pull/398) and fully passes the test suites CXF has at the moment. It brings significant improvement in terms of getting rid of additional transport (SSE), dependencies (Atmosphere) and implementation complexity.

### CODE REVIEW

**Comment by reta** [comment]
@andymc12 could you by any chance help with verifying the implementation against JAX-RS 2.1 TCK (SSE)?

**Comment by reta** [comment]
@johnament @rmannibucau could you guys take a look / try it out, this is one of the improvements regarding SSE implementation in CXF we have discussed a while ago.

**Comment by rmannibucau** [comment]
@reta looks overall good, I have 2 questions:

1. does setting org.apache.cxf.jaxrs.bus.providers prevent to do  it elsewhere? If so it should more be an append no?
2. can you try to run https://github.com/apache/meecrowave/tree/trunk/integration-tests/sse upgrading cxf version locally? if the test passes it sounds good for me

**Comment by reta** [comment]
@rmannibucau While I am looking into 1st issue (I see you use similar approach in Meecrowave) to make sure it works properly, here are the full build, with all tests run against this branch (I commented out SSE transport and Atm-related settings):

```
[INFO]
[INFO] Meecrowave ........................................ SUCCESS [  3.254 s]
[INFO] Meecrowave :: Specs API ........................... SUCCESS [  6.273 s]
[INFO] Meecrowave :: Core ................................ SUCCESS [ 57.949 s]
[INFO] Meecrowave :: Maven ............................... SUCCESS [ 14.841 s]
[INFO] Meecrowave :: Gradle .............................. SUCCESS [  1.841 s]
[INFO] Meecrowave :: JUnit ............................... SUCCESS [ 16.995 s]
[INFO] Meecrowave :: Arquillian .......................... SUCCESS [  7.544 s]
[INFO] Meecrowave :: JPA ................................. SUCCESS [  7.935 s]
[INFO] Meecrowave :: Jolokia ............................. SUCCESS [  8.663 s]
[INFO] Meecrowave :: OAuth2 .............................. SUCCESS [ 16.975 s]
[INFO] Meecrowave :: Doc ................................. SUCCESS [ 53.197 s]
[INFO] Meecrowave :: JTA ................................. SUCCESS [  7.819 s]
[INFO] Meecrowave :: Integration Tests ................... SUCCESS [  0.142 s]
[INFO] Meecrowave :: Integration Tests :: Groovy ......... SUCCESS [ 10.410 s]
[INFO] Meecrowave :: Integration Tests :: Bean Validation  SUCCESS [  5.640 s]
[INFO] Meecrowave :: Integration Tests :: WebServices .... SUCCESS [  8.429 s]
[INFO] Meecrowave :: Integration Tests :: Ssl ............ SUCCESS [ 14.183 s]
[INFO] Meecrowave :: Integration Tests :: Server Side Events  SUCCESS [  6.810 s]
[INFO] Meecrowave Samples ................................ SUCCESS [  0.253 s]
[INFO] Meecrowave Samples - REST (trivial) ............... SUCCESS [  4.867 s]
[INFO] Meecrowave Samples - REST ......................... SUCCESS [  4.813 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by rmannibucau** [comment]
Got the same result so just the 1st point to validate (i got a broken case but maybe i tested it wrong) and +1 from me.

**Comment by reta** [comment]
@rmannibucau Thanks for help, pushed the latest changes. Providers are append, the `Meecrowave` tests should be stable and green. One of the major behavior changes is that `send` is truly async now, which is awesome, while with Atm it was sync, returning the completed future every time.

**Comment by reta** [comment]
@johnament  @andymc12 Any concerns guys from Microprofile side / other integrations? The implementation looks pretty good so far, would be great to get it in before next release, major improvement.

**Comment by rmannibucau** [comment]
+1

**Comment by reta** [comment]
Thanks @andymc12, targeting merge for this week, working on documentation update.

**Comment by csierra** [comment]
thank you guys!
and also thanks to @rotty300 and @timothyjward for their help with this...

**Comment by reta** [comment]
Thank YOU guys! @csierra in case it would be possible for your project(s) to upgrade to 3.2.5 (once released), getting the feedback about SSE would be awesome. Thank you!

**Comment by csierra** [comment]
yup... are you planning to release soon?

**Comment by reta** [comment]
yes, in the next couple of weeks (hopefully!) :)

**Comment by csierra** [comment]
hey @reta... do you have any updates on the release date?

**Comment by dkulp** [comment]
There is an "issue" in Santuario (which CXF depends on) that is being investigated which is holding up WSS4J and CXF releases

**Comment by csierra** [comment]
:-/ I see... thx for the update!

**Pull request merged**
