### PR TITLE
[CXF-8758]:Add wiremock-standalone test dependency to fix all tests u…

### PR DESCRIPTION
**Pull request by jimma**
…nder microprofile-client module

### CODE REVIEW

**Comment by reta** [comment]
> @reta It seems we pull the com.github.tomakehurst:wiremock-standalone:2.27.2 test scope dependency and it works for all tests under rt/rs/microprofile-client and systests/jaxrs/JAXRSClientMetricsTest. Although this imports some javax servelt and jetty9 artifacts , but they are all for test purpose and doesn't pollute any microprofile client and system test client side dependencies. After the wiremock jakarta version is ready ,we can change back to use the com.github.tomakehurst:wiremock dependency to imports the jakarta servelt and jetty11 dependency. If you want me to include wiremock change for system/jaxrs, please let me know.

This is useful trick, thanks @jimma ! Do you think we could wait a bit before merging this one (🤞 the we would have wiremock snapshots available)? For `system/jaxrs` I was thinking to phase wiremock out (it is used in very limited scope), working on that.

**Comment by jimma** [comment]
> This is useful trick, thanks @jimma ! Do you think we could wait a bit before merging this one (🤞 the we would have wiremock snapshots available)?

@reta  I'd prefer to add this to upstream to show how many jakarta failures left we need to fix before we have a wiremock(with jetty11 update) snapshot available.  Because update to wiremock snapshot could be one line change , and it's easy to change after it's available. WDYT ?

> For `system/jaxrs` I was thinking to phase wiremock out (it is used in very limited scope), working on that.
That's very cool.  Thanks @reta !

**Comment by reta** [comment]
> > This is useful trick, thanks @jimma ! Do you think we could wait a bit before merging this one (crossed_fingers the we would have wiremock snapshots available)?
> 
> @reta I'd prefer to add this to upstream to show how many jakarta failures left we need to fix before we have a wiremock(with jetty11 update) snapshot available. Because update to wiremock snapshot could be one line change , and it's easy to change after it's available. WDYT ?
> 
> > For `system/jaxrs` I was thinking to phase wiremock out (it is used in very limited scope), working on that.
> > That's very cool.  Thanks @reta !

@jimma sure, no objections, could you please rebase / merge with main? thank you.

**Comment by jimma** [comment]
Done. Thanks @reta.

**Comment by reta** [comment]
> Done. Thanks @reta.

Thanks @jimma but I don't see it making the difference:

```
```

**Comment by jimma** [comment]
@reta  It looks I missed another commit and sent it with another PR : https://github.com/apache/cxf/pull/1018.

**Pull request merged**
