### PR TITLE
CXF-8206 Update to saaj-impl 1.5.2

### PR DESCRIPTION
**Pull request by amarkevich**

### CODE REVIEW

**Comment by deki** [comment]
Seems to work but I haven't check osgi. I think we should target 3.4.0 for merge...

**Comment by coheigea** [comment]
@amarkevich Can you rebase the branch off master?

**Comment by amarkevich** [comment]
@coheigea done

**Comment by coheigea** [comment]
@ffang  - Any objections?

**Comment by ffang** [comment]
@amarkevich @coheigea 
Sorry for the late reply.

I tested OSGi related tests both with JDK8 and 11, all passed, so I think we are good to go!

Freeman

**Pull request merged**
