### PR TITLE
[CXF-7339] Fix NPE due to weak reference being GC-ed

### PR DESCRIPTION
**Pull request by asoldano**
https://issues.apache.org/jira/browse/CXF-7339

### CODE REVIEW

**Comment by asoldano** [comment]
@andymc12 , actually I expected a concern about this, that's why I opened up a PR instead of committing directly. I'm not sure we want to keep the former behavior wrt supporting null keys. I don't think entries with null keys were actually used before, null keys happened to be "supported" because of the internal implementation detail choice. This said I believe the code that I fixed is not calling remove(null) on purpose, basically the change here is exposing a bug that was there before.
@dkulp what's your opinion on this?

**Comment by dkulp** [comment]
I actually think doing "both" would be the right thing to do.   The fix in this PR is likely correct as calling remove with a null key is pointless as there shouldn't ever be a null "Set" of classes as a key in the cache.  Possibly and empty set, but likely not a null set.

However, protecting against it in the CacheMap is also a good thing.

**Comment by asoldano** [comment]
@andymc12 I've added another commit for the changes in the CacheMap, hopefully this should be enough.

**Comment by dkulp** [comment]
Yea... that looks good to me.

**Comment by asoldano** [comment]
OK, thanks, I've merged the PR.

**Pull request merged**
