### PR TITLE
Switching to ActiveMQ Artemis

### PR DESCRIPTION
**Pull request by reta**
Switching to ActiveMQ Artemis

### CODE REVIEW

**Comment by coheigea** [comment]
@reta Why did you make this change? CXF committers have a history with and still use AMQ Classic, I think I'd prefer that this change wasn't made. I'm also a bit confused about the OpenSAML changes in this PR - why were they needed for a change to ActiveMQ?

**Comment by jimma** [comment]
@coheigea  It looks this is for CXF jakarta namespace change. From [ActiveMQ Artemis embraces Jakarta EE ]( https://blogs.apache.org/activemq/entry/activemq-artemis-embraces-jakarta-ee), Artemis now has the jakarta namespace release.

**Comment by rmannibucau** [comment]
+1 @coheigea , artemis has no link with ActiveMQ (known as v5) so this is a huge breaking change - we evaluated it at TomEE some years ago and it was not even an option :(. Maybe just request to AMQ project or do in cxf a jakarta shade/relocation which would enable users to not be broken. TomEE did it with success for ex (https://tomee.apache.org/tomee-9.0/docs/jms-resources-and-mdb-container.html) so worse case you can grab the AMQ from tomee too.

**Comment by reta** [comment]
@coheigea @rmannibucau referring @jimma comment, the ActiveMQ Classic does not support Jakarta nor JMS 2.0+, so we have 2 + 1 choices here: 
 - migrate to ActiveMQ Artemis (JMS 1.1 & 2.0 + Jakarta Messaging 2.0 & 3.0)
 - drop JMS transport altogether 
 - ask ActiveMQ guys to provide JMS 1.1 & 2.0 + Jakarta Messaging 2.0 & 3.0 for Classic (I hope we won't consider "patching" of ActiveMQ artifacts in CXF) or evaluate if TomEE approach applies to CXF

@coheigea Regarding SAML changes, those are introduced by WSS4J / SAML 4.x updates, the Joda dependencies are gone in favor of Java Standard Library.

@coheigea @rmannibucau I could revert the ActiveMQ Artemis change (although our JMS transport depends on API only, the tests exercise against the brokers), please let me know what do you think, thanks!

**Comment by coheigea** [comment]
@reta Regarding OpenSAML, the work was already done on this branch - https://github.com/apache/cxf/tree/opensaml4, but only in the context of updating to WSS4J 2.5.x / OpenSAML 3.4.x. I think it's better to consider it separately from Artemis.

**Comment by reta** [comment]
@coheigea @rmannibucau change reverted , thanks a for promtp feedback!

**Comment by rmannibucau** [comment]
@reta my 2cts would be to use JMS 1.1 API (JMS 2.0 API is not needed in CXF and does not bring anything AFAIK) and let the user provide the API he wants for most usages. For the distro I would prefer to add one of the AMQ 5 relocation but artemis is fine too there. Note that there are some JMS 2 work for AMQ 5 (mainly importing https://github.com/apache/tomee/tree/master/container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2) so I think it would be worth pinging AMQ guys to get it faster, agree it is really overdue today but in terms of features and deployment I don't think switching the provider is user friendly....until it is not used ;) - but not data on that on my side.

**Comment by jimma** [comment]
@reta @coheigea @rmannibucau  I just read this from [activemq.apache.org](https://activemq.apache.org/) : 

"There are currently two "flavors" of ActiveMQ available - the well-known "classic" broker and the "next generation" broker code-named Artemis. Once Artemis reaches a sufficient level of feature parity with the "Classic" code-base it will become the next major version of ActiveMQ. Initial [migration documentation](https://activemq.apache.org/components/artemis/migration) is available as well as a development [roadmap](https://activemq.apache.org/activemq-artemis-roadmap) for Artemis. "

It looks the Artemis is the future version of ActiceMQ, so in the future we need to migrate to Artemis ?

**Comment by reta** [comment]
@jimma this was/is my understanding as well

**Comment by jbertram** [comment]
Hey folks. I'm on the ActiveMQ PMC and I can confirm what @jimma has said. The goal of the ActiveMQ community is to make Artemis the next major version of ActiveMQ (i.e. 6.0). 

I'm not clear on the entire use-case here, but if you're embedding ActiveMQ and using it internally then it should be a pretty straight-forward migration assuming you aren't making use of many ActiveMQ-specific features. Looking through @reta's PR it looks pretty much as I would expect.

For what it's worth I'm looking at helping TomEE support ActiveMQ Artemis right now based on a recent [discussion like this](https://lists.apache.org/list?dev@activemq.apache.org:lte=1M:Jakarta%20compatible%20version%20of%20ActiveMQ%20classic) on the ActiveMQ dev list, although I've been covered up with other work recently.

I think the sooner projects like CXF, TomEE, etc. migrate the better position we'll _all_ be in. At the very least it will reduce pressure on ActiveMQ to duplicate work on the "Classic" broker that's already been done on Artemis.

I'm willing to answer any questions anybody has, technical or otherwise, about CXF's potential migration to Artemis. I would volunteer to help with the coding, but @reta seems to have that in hand already.

**Comment by reta** [comment]
Thanks a lot @jbertram, it sounds very reassuring, thank you for confirming. There are 2 migration paths which I have not addressed yet:
 - Artemis + JTA (Jakarta TM)
 - Alternative to ActiveMQ Advisories [1], do you happen to know if there are replacements in Artemis? If you ask me why we got it in the first place - I don't know that exactly (yet), besides reversing engineering the implementation.

Thanks a mill!

[1] https://activemq.apache.org/advisory-message

**Comment by rmannibucau** [comment]
Hi @jbertram for what it's worth:

1. Tomee already runs well with artemis if you add it
2. Migration for users is almost always hard or impossible for a tons of reasons (particular feature missing - there are still a lot, undesired dependencies, too huge stack, too much "new" redhat stuff/"not apache" dep - important for support for ex, unsupported protocol, inexperience of ops, too hard/impossible smooth migration on existing clusters - hundreds of instances are not rare, less smoother getting started, ...).

I know goal of amq 6 was to make it converging but it never happent since the creation even if a lot of - good - efforts had been done so i would be very cautious with such statements.
As mentionned, code migration can be 1h or alike, rest will never happen and we were talking of distro so prod so think we should stick to amq5 still since artemis didnt manage to replace it in adoption yet.

**Comment by reta** [comment]
@rmannibucau if you remember, we have discussed to have `javax.*` branch (taking about CXF specifically), in sync with `jakarta.*` one. We have not done anything in this direction just yet, but won't be this path a viable option for once who would stay on AMQ 5.x ?

**Comment by rmannibucau** [comment]
@reta agree but think it will be the exception confirming the general rule (:()). I also saw a ticket for AMQ 5 moving to jakarta but agree overall that javax -> AMQ5 (too much users), jakarta -> artemis (new users since it requires migration effort anyway). There is also this topic about splitting cxf in modules, I strongly think JMS integration can be extracted since it almost never moves, wdyt? My overall goal is to keep AMQ 5 user having a functional distro and not have to start doing it manually for the time cxf maintains javax branch.

**Comment by jbertram** [comment]
@reta 

> Artemis + JTA (Jakarta TM)

As far as I know this should work fine.

> Alternative to ActiveMQ Advisories [1], do you happen to know if there are replacements in Artemis?

Artemis has [management notifications](https://activemq.apache.org/components/artemis/documentation/latest/management.html#management-notifications), as well as the the [NotificationActiveMQServerPlugin](https://activemq.apache.org/components/artemis/documentation/latest/broker-plugins.html#using-the-notificationactivemqserverplugin) (which expands the kinds of notifications which are sent). However, that's not a direct replacement for advisory messages and may not fit your need depending on what you're using advisories for. We can discuss further if needed.

**Comment by jimma** [comment]
@reta  I tried to build the jms with the Artemis change. There are couple of test failures : 
`
[ERROR] Failures:
[ERROR]   JMSDestinationTest.testDoNotCreateSecurityContext:545->testSecurityContext:558->AbstractJMSTester.waitForReceiveDestMessage:278 Can't receive the Destination message in 10 seconds
[ERROR]   JMSDestinationTest.testProperty:424->verifyRequestResponseHeaders:303 The message encoding should be equal expected:<U[TF-8]> but was:<U[S-ASCII]>
[ERROR]   JMSDestinationTest.testRoundTripDestination:316 SecurityContext should be set in message received by JMSDestination
[ERROR]   JMSDestinationTest.testSecurityContext:538 SecurityContext should be set in message received by JMSDestination
[ERROR]   JMSDestinationTest.testTemporaryQueueDeletionUponReset:511
Expected: <1>
     but: was <0>
[ERROR]   MessageListenerTest.testConnectionProblemXA:98
[ERROR]   MessageListenerTest.testLocalTransaction:158->testTransactionalBehaviour:176->assertNumMessagesInQueue:212 Should be rolled back -> number of messages on queue expected:<1> but was:<0>
[ERROR]   MessageListenerTest.testWithJTA:117->testTransactionalBehaviour:176->assertNumMessagesInQueue:212 Should be rolled back -> number of messages on queue expected:<1> but was:<0>
[INFO]
[ERROR] Tests run: 65, Failures: 8, Errors: 0, Skipped: 1
`
Are these some behaviors change or we need to fix the these tests ?

**Comment by reta** [comment]
> @reta I tried to build the jms with the Artemis change. There are couple of test failures :
> 
> > [ERROR] Failures:
> > [ERROR]   JMSDestinationTest.testDoNotCreateSecurityContext:545->testSecurityContext:558->AbstractJMSTester.waitForReceiveDestMessage:278 Can't receive the Destination message in 10 seconds
> > [ERROR]   JMSDestinationTest.testProperty:424->verifyRequestResponseHeaders:303 The message encoding should be equal expected:<U[TF-8]> but was:<U[S-ASCII]>
> > [ERROR]   JMSDestinationTest.testRoundTripDestination:316 SecurityContext should be set in message received by JMSDestination
> > [ERROR]   JMSDestinationTest.testSecurityContext:538 SecurityContext should be set in message received by JMSDestination
> > [ERROR]   JMSDestinationTest.testTemporaryQueueDeletionUponReset:511
> > Expected: <1>
> > but: was <0>
> > [ERROR]   MessageListenerTest.testConnectionProblemXA:98
> > [ERROR]   MessageListenerTest.testLocalTransaction:158->testTransactionalBehaviour:176->assertNumMessagesInQueue:212 Should be rolled back -> number of messages on queue expected:<1> but was:<0>
> > [ERROR]   MessageListenerTest.testWithJTA:117->testTransactionalBehaviour:176->assertNumMessagesInQueue:212 Should be rolled back -> number of messages on queue expected:<1> but was:<0>
> > [INFO]
> > [ERROR] Tests run: 65, Failures: 8, Errors: 0, Skipped: 1
> 
> Are these some behaviors change or we need to fix the these tests ?

@jimma thank you, those are expected, I mentioned TODOs https://github.com/apache/cxf/pull/919#issuecomment-1067260885 a few tests are failing but I was planning to address them later on (however we reverted).

**Pull request merged**
